[workspace]
members = [
    "contracts/campaign",
    "contracts/donation",
    "contracts/verification",
    "tests/integration"
]


resolver = "2"

[workspace.dependencies]
soroban-sdk = "21.2.0"
stellar-strkey = "0.0.7"
rand = "0.8.5"


